### ISSUE TITLE
documentation of cache events

### ISSUE THREAD

**Issue by WebFreak001** [ikod/cachetools#10]
What's the difference between removed and evicted? Also the documentation doesn't include documentation for the CacheEvent struct, so I had to search across all the source code to figure out what the event type member is (it's `.event`)

**Comment by ikod** [comment]
hello @WebFreak001 !
"Evicted" generated when data evicted from cache due to the TTL or any other restriction (like limit on total number of items in cache). "Removed" - means you explicetely removed data.
Thanks for your issue, I'll fix this.

**Comment by WebFreak001** [comment]
I would expect Expired to be the event when TTL is over, are you sure it's Evicted?

Can multiple events fire when an item is removed?

**Comment by ikod** [comment]
@WebFreak001 

sorry, I answered without looking to sources.
So...
**Evicted** can be result of `put` in case you have to evict some items from cache like https://github.com/ikod/cachetools/blob/master/source/cachetools/cachelru.d#L193
**Expired** can be result of `get` if you trying to get expired item (https://github.com/ikod/cachetools/blob/master/source/cachetools/cachelru.d#L135)
**Removed** - result of `remove` or `clear` call (https://github.com/ikod/cachetools/blob/master/source/cachetools/cachelru.d#L236). For clear you'll get events with all removed items.

For 2Q cache you can receive Evictet even after `get` as 2Q use several queues which can be updated and filled during get.

Hope it helps!

**Comment by WebFreak001** [comment]
thanks, could you add that to the documentation? Also preferably specify that any remove event may only occur once, to make sure future code doesn't break that constraint either.

**Comment by ikod** [comment]
Thanks for report, I added docs in README.md
